### PR TITLE
cli: migrate from urfave/cli/v1 to urfave/cli/v2

### LINKED ISSUE #262: Migrate the Main App from urfave/cli to urfave/cli/v2
The v2 has a number of nice features, but before we can take advantage of them we need to do a basic migration to the new version.

There's a nice migration guide:

https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md

### PR DESCRIPTION
**Pull request by mritunjaysharma394**
Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>

[Fixes-262](https://github.com/docker-slim/docker-slim/issues/262)
==================================================================
This PR fixes #262 

What
===============
Migrates the Main App from urfave/cli to urfave/cli/v2

Why
===============
Taking advantage of the new version of urfave/cli

How Tested
===============
Locally

### CODE REVIEW

**Comment by kcq** [comment]
Thanks a lot for the PR @mritunjaysharma394 ! Quite a lot there :) Nice catch with those BoolTFlag changes too.

**Comment by mritunjaysharma394** [comment]
Thank you so much for the review and your kind words,  @kcq :-)

really means a lot, I will also propose changes to their migrate guide too so that changes like BoolTFlags, Going away of GlobalString, etc and NewStringSlice are reflected there :)

**Comment by kcq** [comment]
@mritunjaysharma394 Good idea! Their guide definitely needs more info. Now it'll be interesting to see if there are any unexpected gotchas :) I wish they'd still allow the flags anywhere, but in v2 they need to be first.

**Comment by mritunjaysharma394** [comment]
Yes @kcq, for now I have created a PR for them https://github.com/urfave/cli/pull/1319 and also hoping that we don’t face unexpected gotchas and even if we do, we will solve it :)

thanks for all the help!

**Comment by kcq** [comment]
nice PR!

**Comment by mritunjaysharma394** [comment]
Thanks a lot :)

**Pull request merged**
