### PR TITLE
Dependencies and Markdown

### PR DESCRIPTION
**Pull request by edumco**
1. Fixes Markdown issues 
2. Upgrades dependencies (via Dependabot)
3. Optimize images (via ImgBotApp)

### CODE REVIEW

**Comment by kcq** [comment]
Looks good except for the Dependabot bits... Not sure if those changes will have side effects or not, so to be on the safe side it would good to exclude those.

**Comment by edumco** [comment]
I will remove promptly

**Comment by edumco** [comment]
@kcq I reverted the changes but felt like a bad approach. What do you think?

**Comment by x-private-one** [comment]
should be ok to revert

**Comment by kcq** [comment]
should be ok to revert :)

**Comment by x-private-one** [comment]
reverting didn't quite work :)

**Comment by kcq** [comment]
reverting didn't quite work :)

**Comment by edumco** [comment]
So it's better remove and will create another copy of the master branch without the dependabot stuff

**Pull request merged**
