### PR TITLE
Arm build

### PR DESCRIPTION
**Pull request by jishminor**
Add support for 32 bit arm

### CODE REVIEW

**Comment by kcq** [comment]
Thank you Josh for the PR! Just to double check... Is there a specific reason you decided to duplicate the ptrace monitoring for arm? The PR also shows that it'll be good to pull in those extra dependencies (e.g., the system package), but i'll be happy to do it myself after the PR is merged.

**Comment by jishminor** [comment]
For ptrace monitoring, when obtaining the syscall number and return value, currently, you use PtraceRegs from the syscall packages which references RAX from the x86 register set. For aarch32, syscall numbers are placed in R7 and return value goes in R0. This is reflected in the use of `regs.Uregs[7]` I am new to Go, so wasn't sure if it would be better practice to split out the files, or query the architecture at runtime. What do you think?

**Comment by kcq** [comment]
Josh, do you mind checking if the ARM functionality still works after the current refactor.

**Comment by jishminor** [comment]
Yes I'll go ahead and do that. I have also been working on the arm64 port, however there seems to be an issue with the ptrace module. It may take me some time to work out. I found this article which may shed some light on a potential issue: https://www.edn.com/Home/PrintView?contentItemId=4440662

**Comment by kcq** [comment]
Sounds good! Saw the same blog post on Undo's blog too :-) https://undo.io/resources/arm64-vs-arm32-whats-different-linux-programmers/

**Comment by jishminor** [comment]
Arm build works after the refactor upon simple inspection. I was not able to get the arm64 ptrace working yet, as it still doesn't appear that there is go support for the differences mentioned in the articles we referenced. I am playing around with some things now. Essentially, we just need to translate: 

ptrace(PTRACE_GETREGS, 0, 0, regs); // for arm32

to

ptrace(PTRACE_GETREGSET, 0, (void*) NT_PRSTATUS, &my_iovec); // for arm64

If you look at the current version of "golang.org/x/sys/unix" which is supposed to be the syscall package replacement, there is is file zptracearm_linux.go, however even it appears to get the call wrong for arm64 file [here](https://github.com/kubernetes-sigs/krew/blob/58ca28838a12eea8ea9ad8f92ad9866e1ced38aa/vendor/golang.org/x/sys/unix/zptracearm_linux.go#L35)

**Pull request merged**
